on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: EU-NL-APD01S01-N01.synthcloud.nl
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2022
          uploads: |
            ./WWW => ./www/
          ignore: |
            ./sites/
            sites/
            **/sites/**
          delete: true
