on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push to SFTP
        uses: AbleLincoln/push-to-sftp@v1.0
        with:
          host: EU-NL-APD01S01-N01.synthcloud.nl
          port: 2022
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          sourceDir: ./www
          targetDir: ./www
